[workspace]
members = [
    "language_parsers",
    "file_system",
    "output_generator",
    "config_manager",
    "cli_tool",
]

# release profile
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
incremental = false
