[package]
name = "cli_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file_system = { path = "../file_system" }
language_parsers = { path = "../language_parsers" }
